### PR TITLE
feat: add footer component

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**

### CODE REVIEW

**Comment by Extheoisah** [comment]
Can you please share screenshots of the component UI?

**Comment by Emmanuel-Develops** [comment]
> Can you please share screenshots of the component UI?

Okay. if ran on dev with storybook `yarn dev`, the component is showcased there.
here are some screenshots.

Screenshot 2024-08-17 at 6 39 08 PM

Screenshot 2024-08-17 at 6 39 15 PM

**Comment by Extheoisah** [comment]
Tested locally and it works well. Can you please rebase on the main branch?

**Comment by Extheoisah** [comment]
Is responsiveness something we want to handle out of the box? Because its not aligned on mobile and table screens
image

**Comment by Emmanuel-Develops** [comment]
> Is responsiveness something we want to handle out of the box? Because its not aligned on mobile and table screens

yes, for components like this, which are meant to be opinionated, the footer shouldn't have drastic changes across projects.
And with the way it is set up, one can opt out of the rendering for sub-components by wrapping the component with their custom component, or passing the className prop

Here is the mobile from the registry figma:
Screenshot 2024-08-18 at 4 15 30 PM

**Review by Extheoisah — APPROVED** [review]

**Pull request merged**
